LangaN_Assign1/LangaN_Assign1/Models/Event.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace LangaN_Assign1.Models
{
    public class Event
    {
        public int EventId { get; set; }

        [Required]
        public string EventTitle { get; set; }

        [DisplayName( "Description")]
        public string EventDescription { get; set; }

        [DisplayName( "Start date")]
        public DateTime EventStartDate { get; set; }

        [DisplayName("End date")]
        public DateTime? EventEndDate { get; set; }

        [Required]
        [DisplayName( "Location")]
        public string EventLocation { get; set; }

        [Required]
        public int EventMaxAttendees { get; set; }

        public int EventRegistrations { get; set; } = 0;
        
        public ICollection<Attendee> Attendees { get; set; }
    }
}

LangaN_Assign1/LangaN_Assign1/Controllers/AttendeeController.cs
using LangaN_Assign1.Data;
using LangaN_Assign1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LangaN_Assign1.Controllers
{
    public class AttendeeController : Controller
    {
        private readonly IEventRepository _eventRepository;

        public AttendeeController(IEventRepository eventRepository)
        {
            _eventRepository = eventRepository;
        }

        [HttpGet]
        public IActionResult Register(int eventId)
        {
            Event eventDetails = _eventRepository.GetEventById(eventId);

            if (eventDetails == null)
            {
                return NotFound();
            }

            var eventRegistration = new Attendee { EventId = eventId };
            return View(eventRegistration);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(Attendee attendee)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    Event Event = _eventRepository.GetEventById(attendee.EventId);

                    if (Event != null)
                    {
                        Event.EventRegistrations++;
                    }

                    _eventRepository.AddAttendees(attendee);
                    _eventRepository.SaveChanges();

                    return RedirectToAction("Confirmation", new { eventId = attendee.EventId });
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. " +
                       "Try again, and if the problem persists, " +
                       "see your system administrator.");
                }
            }
            return View(attendee);
        }
        public IActionResult List(Attendee attendee)
        {
            var Attendee = _eventRepository.GetAllAttendees().ToList();
            return View(Attendee);
        }

        [HttpGet]
        public  IActionResult Confirmation(int eventId)
        {
            Event events = _eventRepository.GetEventWithAttendees(eventId);

            if (events == null)
            {
                return NotFound();
            }
            return View(events);
        }
    }
}

LangaN_Assign1/LangaN_Assign1/Controllers/EventController.cs
using LangaN_Assign1.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LangaN_Assign1.Controllers
{
    public class EventController : Controller
    {

        private readonly EntityDbContext _context;

        public EventController(EntityDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Events.ToListAsync());
        }

        public async Task<IActionResult> Details(int? eventId)
        {
            if (eventId == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.EventId == eventId);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }
    }
}

LangaN_Assign1/LangaN_Assign1/Views/Event/Details.cshtml
@model Event

<h2>@ViewData["Title"]</h2>

    <partial name="_EventDetails" model="@Model"/>
    <p>
      
           @if (Model.EventRegistrations < Model.EventMaxAttendees) 
           {
              @if (User.Identity.IsAuthenticated && !(User.IsInRole("Admin")))
              {
                 <a asp-controller="Attendee" asp-action="Register" 
                 asp-route-eventId="@Model.EventId"
                 class="btn btn-primary">Register</a>
              } 
           }
        <a asp-action="Index" class="btn btn-outline-primary">Return to Home Page</a>

       
    </p>

LangaN_Assign1/LangaN_Assign1/Views/Event/Index.cshtml
@model IEnumerable<Event>

<div class="rounded text-center text-light bg-primary p-5 my-3">
    <h1>Welcome to the Event Management System</h1>
    <p>Find and register for awesome events happening near you!</p>
</div>

<h3 class="text-primary">Upcoming Events</h3>

@if (Model.Any())
{
    <table class="table table-bordered">
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <h4>@item.EventTitle</h4>

                        @* Event Title *@
                        <div>@item.EventStartDate.ToShortDateString()</div> @* Event Start Date *@
                        <a asp-action="Details" asp-controller="Event" asp-route-eventId="@item.EventId" class="btn btn-primary my-3">View Details</a>

                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-action="List" asp-controller="Attendee" asp-route-AttendeeId="@item.Attendees" class="btn btn-primary my-3">View Attendes</a>

                        }
                       
                    </td>
                </tr>
            }
           
        </tbody>
    </table>
}
else
{
    <p>No upcoming events found at this time.</p>
}